<!DOCTYPE html>
<html lang="pt"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Diogo B. Provete">
  <title>Análise de Dados Univariados – ANOVA, ANCOVA e interações como modelos lineares</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-88dd1b2681489070f5a94c6e1b58dfd2.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="ANOVA, ANCOVA e interações como modelos lineares – Análise de Dados Univariados">
<meta property="og:description" content="Encontro 3 · Análise de Dados Univariados · PPGBA/UFMS">
<meta property="og:site_name" content="Análise de Dados Univariados">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">ANOVA, ANCOVA e interações como modelos lineares</h1>
  <p class="subtitle">Encontro 3 · Análise de Dados Univariados · PPGBA/UFMS</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Diogo B. Provete 
</div>
</div>
</div>

  <p class="date">22 de setembro de 2026</p>
</section>
<section id="onde-estamos-no-ciclo-ppdac" class="slide level2">
<h2>Onde estamos no ciclo PPDAC</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="e03_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center" style="width:36.0%"></p>
</figure>
</div>
</div>
</div>
<p>Continuamos na <strong>Análise</strong>. O que muda hoje vem inteiramente do <strong>Plano</strong>: quantos fatores, balanceado ou não, com ou sem covariável.</p>
</section>
<section id="onde-paramos" class="slide level2 secao">
<h2>Onde paramos</h2>
<p>Ontem: teste t é <code>lm(y ~ grupo)</code> com uma coluna 0/1.</p>
<div class="definicao">
<p>Hoje: mais colunas na mesma matriz. <strong>Nenhum conceito novo de inferência.</strong></p>
</div>
<ul>
<li>3 grupos em vez de 2 → ANOVA de um fator</li>
<li>2 fatores → ANOVA fatorial</li>
<li>fator + covariável contínua → ANCOVA</li>
<li>o produto das colunas → interação</li>
</ul>
</section>
<section id="hoje" class="slide level2">
<h2>Hoje</h2>
<ol type="1">
<li><em>Productive failure</em> de abertura</li>
<li>ANOVA de um fator como <code>lm()</code></li>
<li>De onde vem a tabela de ANOVA</li>
<li>Dois fatores e interação</li>
<li><strong>Intervalo</strong></li>
<li>ANCOVA e homogeneidade de inclinações</li>
<li>Somas de quadrados I, II e III</li>
<li>Comparações com <code>emmeans</code></li>
<li>Como relatar</li>
</ol>
</section>
<section id="productive-failure" class="slide level2">
<h2><em>Productive failure</em></h2>
<p>Vocês têm 223 lagartos <em>Coleodactylus meridionalis</em>, com sexo, comprimento rostro-cloacal (SVL) e comprimento da cauda regenerada após autotomia.</p>
<div class="definicao">
<p><strong>Pergunta:</strong> machos e fêmeas regeneram cauda de forma diferente?</p>
</div>
<p>Em grupos, 10 minutos:</p>
<ol type="1">
<li>que análise? escrevam a fórmula;</li>
<li>o que “de forma diferente” significa exatamente — mesma média? mesma relação com o tamanho do corpo?</li>
<li>o que pode dar errado?</li>
</ol>
</section>
<section class="slide level2">

</section>
<section>
<section id="anova-de-um-fator" class="title-slide slide level1 secao center">
<h1>1. ANOVA de um fator</h1>

</section>
<section id="três-espécies-uma-resposta" class="slide level2">
<h2>Três espécies, uma resposta</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="e03_files/figure-revealjs/unnamed-chunk-3-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="os-dois-caminhos-lado-a-lado" class="slide level2 smaller">
<h2>Os dois caminhos, lado a lado</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> species, <span class="at">data =</span> pinguins)</span>
<span id="cb1-2"><a></a><span class="fu">anova</span>(m)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: body_mass_g
           Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
species     2 145190219 72595110  341.89 &lt; 2.2e-16 ***
Residuals 330  70069447   212332                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">summary</span>(<span class="fu">aov</span>(body_mass_g <span class="sc">~</span> species, <span class="at">data =</span> pinguins))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df    Sum Sq  Mean Sq F value Pr(&gt;F)    
species       2 145190219 72595110   341.9 &lt;2e-16 ***
Residuals   330  70069447   212332                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="definicao">
<p><code>aov()</code> é literalmente uma casca em volta de <code>lm()</code>. Mesmo <em>F</em>, mesmos graus de liberdade, mesmo <em>p</em>.</p>
</div>
</section>
<section id="primeiro-a-tabela-de-códigos" class="slide level2 smaller">
<h2>Primeiro, a tabela de códigos</h2>
<p>No Encontro 2 uma coluna 0/1 bastava, porque havia dois grupos. Com três, o R cria <strong>duas</strong> colunas:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Espécie</th>
<th style="text-align: center;"><code>speciesChinstrap</code></th>
<th style="text-align: center;"><code>speciesGentoo</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Adelie</code> (referência)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Chinstrap</code></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Gentoo</code></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<div class="definicao">
<p>A referência <strong>não ganha coluna própria</strong>. Ela é a linha de zeros — o caso que sobra quando todas as outras colunas valem 0.</p>
</div>
<p>Regra geral: <span class="math inline">\(k\)</span> grupos, <span class="math inline">\(k-1\)</span> colunas.</p>
</section>
<section id="a-matriz-uma-linha-de-cada-espécie" class="slide level2 smaller">
<h2>A matriz, uma linha de cada espécie</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(m)</span>
<span id="cb5-2"><a></a>X[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">266</span>, <span class="dv">147</span>), ]   <span class="co"># 1 é Adelie, 266 é Chinstrap, 147 é Gentoo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept) speciesChinstrap speciesGentoo
1             1                0             0
266           1                1             0
147           1                0             1</code></pre>
</div>
</div>
<p>A primeira coluna é só de 1: é o intercepto. As outras duas são a tabela do slide anterior, repetida uma vez por pinguim.</p>
</section>
<section id="substituindo-uma-espécie-de-cada-vez" class="slide level2 smaller">
<h2>Substituindo, uma espécie de cada vez</h2>
<p>O modelo é <span class="math inline">\(\hat{y} = \beta_0 \cdot 1 + \beta_1 x_1 + \beta_2 x_2\)</span>. Basta pôr a linha de cada espécie no lugar de <span class="math inline">\(x_1\)</span> e <span class="math inline">\(x_2\)</span>:</p>
<p><strong>Adelie</strong> — linha <span class="math inline">\((1, 0, 0)\)</span>: <span class="math display">\[\hat{y} = \beta_0 + \beta_1 \cdot 0 + \beta_2 \cdot 0 = \beta_0\]</span></p>
<p><strong>Chinstrap</strong> — linha <span class="math inline">\((1, 1, 0)\)</span>: <span class="math display">\[\hat{y} = \beta_0 + \beta_1\]</span></p>
<p><strong>Gentoo</strong> — linha <span class="math inline">\((1, 0, 1)\)</span>: <span class="math display">\[\hat{y} = \beta_0 + \beta_2\]</span></p>
<div class="definicao">
<p><span class="math inline">\(\beta_0\)</span> é a <strong>média de Adelie</strong>. <span class="math inline">\(\beta_1\)</span> e <span class="math inline">\(\beta_2\)</span> são <strong>diferenças</strong> em relação a ela — nenhum dos dois é a média do próprio grupo.</p>
</div>
</section>
<section id="conferindo-na-mão" class="slide level2 smaller">
<h2>Conferindo na mão</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">coef</span>(m)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) speciesChinstrap    speciesGentoo 
      3706.16438         26.92385       1386.27259 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>pinguins <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a></a>  <span class="fu">group_by</span>(species) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a></a>  <span class="fu">summarise</span>(<span class="at">media =</span> <span class="fu">mean</span>(body_mass_g)) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a></a>  <span class="fu">mutate</span>(<span class="at">diferenca_para_Adelie =</span> media <span class="sc">-</span> <span class="fu">first</span>(media))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  species   media diferenca_para_Adelie
  &lt;fct&gt;     &lt;dbl&gt;                 &lt;dbl&gt;
1 Adelie    3706.                   0  
2 Chinstrap 3733.                  26.9
3 Gentoo    5092.                1386. </code></pre>
</div>
</div>
<p>O intercepto é 3706 g, que é a média de <code>Adelie</code>. O coeficiente de <code>Gentoo</code> é 1386 g, que é 5092 − 3706. <strong>Os mesmos números, nas duas tabelas.</strong></p>
</section>
<section id="por-que-k-1-e-não-k" class="slide level2 smaller">
<h2>Por que <span class="math inline">\(k-1\)</span> e não <span class="math inline">\(k\)</span></h2>
<p>E se déssemos uma coluna também para <code>Adelie</code>?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>X3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, <span class="at">speciesAdelie =</span> <span class="fu">as.numeric</span>(pinguins<span class="sc">$</span>species <span class="sc">==</span> <span class="st">"Adelie"</span>))</span>
<span id="cb11-2"><a></a></span>
<span id="cb11-3"><a></a><span class="fu">c</span>(<span class="at">colunas =</span> <span class="fu">ncol</span>(X3), <span class="at">posto =</span> <span class="fu">qr</span>(X3)<span class="sc">$</span>rank)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>colunas   posto 
      4       3 </code></pre>
</div>
</div>
<p>Quatro colunas, posto 3: uma delas é redundante. E dá para ver qual — as três colunas de espécie <strong>somam exatamente a coluna do intercepto</strong>, já que todo pinguim é de uma espécie e só uma.</p>
<div class="nota">
<p>Nesse caso o R não erra: ele descarta uma e devolve <code>NA</code> no coeficiente correspondente. Mas a escolha de qual descartar passa a ser dele, e não sua — e é por isso que existe a ideia de nível de referência.</p>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="de-onde-vem-a-tabela" class="title-slide slide level1 secao center">
<h1>2. De onde vem a tabela</h1>

</section>
<section id="decomposição-da-variação" class="slide level2">
<h2>Decomposição da variação</h2>
<p><span class="math display">\[
\underbrace{\sum (y_i - \bar{y})^2}_{\text{SQ total}} =
\underbrace{\sum (\hat{y}_i - \bar{y})^2}_{\text{SQ do modelo}} +
\underbrace{\sum (y_i - \hat{y}_i)^2}_{\text{SQ residual}}
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>sq_total <span class="ot">&lt;-</span> <span class="fu">sum</span>((pinguins<span class="sc">$</span>body_mass_g <span class="sc">-</span> <span class="fu">mean</span>(pinguins<span class="sc">$</span>body_mass_g))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-2"><a></a>sq_res   <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(m)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb13-3"><a></a><span class="fu">c</span>(<span class="at">total =</span> sq_total, <span class="at">modelo =</span> sq_total <span class="sc">-</span> sq_res, <span class="at">residual =</span> sq_res)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    total    modelo  residual 
215259666 145190219  70069447 </code></pre>
</div>
</div>
<p>Compare com a coluna <code>Sum Sq</code> da tabela de ANOVA. São os mesmos números.</p>
</section>
<section id="o-que-o-f-é" class="slide level2">
<h2>O que o <em>F</em> é</h2>
<p><span class="math display">\[
F = \frac{\text{SQ do modelo} / \text{gl do modelo}}
         {\text{SQ residual} / \text{gl residual}}
\]</span></p>
<div class="definicao">
<p>Variância explicada por observação de modelo, dividida por variância não explicada por observação de resíduo. Se o modelo não explica nada, a razão flutua em torno de 1.</p>
</div>
<p>E <span class="math inline">\(R^2\)</span> é simplesmente SQ do modelo / SQ total:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">c</span>(<span class="at">r2_manual =</span> (sq_total <span class="sc">-</span> sq_res) <span class="sc">/</span> sq_total, <span class="at">r2_lm =</span> <span class="fu">summary</span>(m)<span class="sc">$</span>r.squared)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>r2_manual     r2_lm 
0.6744887 0.6744887 </code></pre>
</div>
</div>
</section>
<section id="por-que-não-fazer-três-testes-t" class="slide level2">
<h2>Por que não fazer três testes t</h2>
<p>Com 3 grupos há 3 comparações; com 5 grupos, 10.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  grupos comparacoes `P(ao menos 1 falso positivo)`
   &lt;int&gt;       &lt;dbl&gt;                          &lt;dbl&gt;
1      2           1                           0.05
2      3           3                           0.14
3      4           6                           0.26
4      5          10                           0.4 
5      6          15                           0.54
6      7          21                           0.66
7      8          28                           0.76</code></pre>
</div>
</div>
<div class="definicao">
<p>A ANOVA faz <strong>um</strong> teste. Quando ele indica diferença, aí sim vamos às comparações específicas — planejadas de preferência, e com correção.</p>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="dois-fatores-e-interação" class="title-slide slide level1 secao center">
<h1>3. Dois fatores e interação</h1>

</section>
<section id="a-pergunta" class="slide level2">
<h2>A pergunta</h2>
<p>Espécie e sexo afetam a massa. <strong>O efeito do sexo é o mesmo nas três espécies?</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="e03_files/figure-revealjs/unnamed-chunk-12-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Retas não paralelas = interação.</p>
</section>
<section id="aditivo-e-com-interação" class="slide level2">
<h2>Aditivo e com interação</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>m_adit <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> species <span class="sc">+</span> sex, <span class="at">data =</span> pinguins)</span>
<span id="cb18-2"><a></a>m_int  <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> species <span class="sc">*</span> sex, <span class="at">data =</span> pinguins)</span>
<span id="cb18-3"><a></a><span class="fu">anova</span>(m_adit, m_int)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: body_mass_g ~ species + sex
Model 2: body_mass_g ~ species * sex
  Res.Df      RSS Df Sum of Sq     F    Pr(&gt;F)    
1    329 32979185                                 
2    327 31302628  2   1676557 8.757 0.0001973 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="definicao">
<p><code>species * sex</code> é abreviação de <code>species + sex + species:sex</code>. O teste compara os dois modelos: vale a pena gastar 2 graus de liberdade com a interação?</p>
</div>
</section>
<section id="a-interação-na-matriz" class="slide level2">
<h2>A interação na matriz</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">colnames</span>(<span class="fu">model.matrix</span>(m_int))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "(Intercept)"              "speciesChinstrap"        
[3] "speciesGentoo"            "sexmale"                 
[5] "speciesChinstrap:sexmale" "speciesGentoo:sexmale"   </code></pre>
</div>
</div>
<p>As duas últimas colunas são <strong>produtos</strong> das anteriores: valem 1 apenas para machos de <code>Chinstrap</code> e machos de <code>Gentoo</code>.</p>
</section>
<section id="interpretando-com-interação" class="slide level2">
<h2>Interpretando com interação</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">round</span>(<span class="fu">coef</span>(m_int), <span class="dv">1</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             (Intercept)         speciesChinstrap            speciesGentoo 
                  3368.8                    158.4                   1310.9 
                 sexmale speciesChinstrap:sexmale    speciesGentoo:sexmale 
                   674.7                   -262.9                    130.4 </code></pre>
</div>
</div>
<div class="definicao">
<p>Com <code>contr.treatment</code>, <code>sexmale</code> <strong>não</strong> é o efeito médio do sexo: é o efeito do sexo <strong>em <code>Adelie</code></strong>, a referência. O efeito em <code>Gentoo</code> é <code>sexmale</code> + <code>speciesGentoo:sexmale</code>.</p>
</div>
<p>Foi por isso que o Encontro 2 insistiu em codificação de fatores.</p>
</section>
<section id="interação-é-resultado-não-estorvo" class="slide level2">
<h2>Interação é resultado, não estorvo</h2>
<div class="definicao">
<p>Em ecologia, a interação costuma ser <strong>a pergunta</strong>, não um incômodo: o efeito da temperatura depende da altitude? O efeito do predador depende da densidade de refúgios?</p>
</div>
<p>Três regras práticas:</p>
<ul>
<li>não interprete efeitos principais isoladamente quando a interação é relevante — interprete o gráfico;</li>
<li>não remova a interação só porque o <em>p</em> passou de 0,05. A decisão é da pergunta, não do limiar;</li>
<li><strong>olhe nas duas direções.</strong> “O efeito da temperatura depende da altitude” e “o efeito da altitude depende da temperatura” são o <strong>mesmo termo</strong> do modelo. Escolher só uma leitura é escolha de narrativa, e costuma ser feita sem perceber.</li>
</ul>
</section>
<section id="a-interação-depende-da-escala" class="slide level2 smaller">
<h2>A interação depende da escala</h2>
<p>Spake et al.&nbsp;(2023) mostram que duas propriedades passam batidas quando se interpreta interação em ecologia. A segunda é a simetria do slide anterior. A primeira é mais incômoda: a <strong>escala de medida</strong> — nas palavras deles,</p>
<blockquote>
<p>whether a response is analysed on an additive or multiplicative scale, such as a ratio or logarithmic scale.</p>
</blockquote>
<div class="definicao">
<p>A mesma relação pode <strong>ter</strong> interação na escala aditiva e <strong>não ter</strong> na multiplicativa, ou o contrário. Não é erro de análise: são perguntas diferentes. “A diferença entre tratamentos é a mesma?” e “a <em>razão</em> entre tratamentos é a mesma?” não são a mesma pergunta.</p>
</div>
<p>Guardem isto para o <strong>Encontro 4</strong>, quando a função de ligação entrar: um GLM com ligação log modela a escala multiplicativa por construção. A escolha da família decide, sem avisar, em que escala você está procurando interação.</p>
</section>
<section id="vendo-acontecer" class="slide level2 smaller">
<h2>Vendo acontecer</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="../assets/spake-2023-fig4.jpg" class="quarto-figure quarto-figure-center" height="410"></p>
</figure>
</div>
<p>Em <strong>B</strong>: riqueza de formigas contra cobertura de gramíneas exóticas, em dois níveis de uso da terra. À esquerda, escala aditiva — as linhas <strong>convergem</strong>, há interação. À direita, os <strong>mesmos dados</strong> em escala multiplicativa — ficam <strong>paralelas</strong>, não há.</p>
<div class="nota">
<p>Figura 4 de Spake, R. et al.&nbsp;2023, <em>Biological Reviews</em> 98:983–1002, <a href="https://doi.org/10.1111/brv.12939">doi:10.1111/brv.12939</a>. Reproduzida sob <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>, sem alterações.</p>
</div>
</section>
<section id="três-erros-com-nome" class="slide level2 smaller">
<h2>Três erros com nome</h2>
<p>O artigo batiza os três modos de errar, e os nomes ajudam a lembrar:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">O que se erra</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Tipo D</strong></td>
<td style="text-align: left;">a <em>detecção</em> e a magnitude — achar interação onde a escala a criou, ou não achar onde a escala a escondeu</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Tipo S</strong></td>
<td style="text-align: left;">o <strong>sinal</strong> da modificação do efeito</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Tipo A</strong></td>
<td style="text-align: left;">o processo por trás — atribuir a um mecanismo biológico o que é artefato de escala</td>
</tr>
</tbody>
</table>
<div class="nota">
<p>Eles mostram que <strong>meta-análise</strong> é especialmente vulnerável aos três, o que importa para quem for por esse caminho: razão de chances e diferença de médias padronizada vivem em escalas diferentes, e a mesma literatura pode dar respostas opostas sobre dependência de contexto conforme a métrica escolhida.</p>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="intervalo" class="title-slide slide level1 secao center">
<h1>Intervalo</h1>
<p>15 minutos.</p>
<p>Na volta: ANCOVA, e por que homogeneidade de inclinações é a ausência de uma interação.</p>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="ancova" class="title-slide slide level1 secao center">
<h1>4. ANCOVA</h1>

</section>
<section id="fator-covariável-contínua" class="slide level2">
<h2>Fator + covariável contínua</h2>
<p>Voltando aos lagartos: a cauda regenerada depende do tamanho do corpo. E o sexo?</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="e03_files/figure-revealjs/unnamed-chunk-16-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="o-modelo" class="slide level2">
<h2>O modelo</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>anc <span class="ot">&lt;-</span> <span class="fu">lm</span>(Autotomized_tail_length <span class="sc">~</span> SVL <span class="sc">+</span> Sex, <span class="at">data =</span> lagartos)</span>
<span id="cb24-2"><a></a><span class="fu">round</span>(<span class="fu">coef</span>(anc), <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         SVL     SexMale 
       3.13        0.31       -0.32 </code></pre>
</div>
</div>
<p>Duas retas <strong>paralelas</strong>: mesma inclinação em relação ao SVL, interceptos diferentes por sexo.</p>
<div class="definicao">
<p>A célebre “premissa de homogeneidade das inclinações” da ANCOVA é exatamente isto: a <strong>ausência da interação</strong> <code>SVL:Sex</code>. Não é uma premissa misteriosa — é uma escolha de modelo, e ela é testável.</p>
</div>
</section>
<section id="testando-a-premissa" class="slide level2">
<h2>Testando a premissa</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>anc_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(Autotomized_tail_length <span class="sc">~</span> SVL <span class="sc">*</span> Sex, <span class="at">data =</span> lagartos)</span>
<span id="cb26-2"><a></a><span class="fu">anova</span>(anc, anc_int)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Autotomized_tail_length ~ SVL + Sex
Model 2: Autotomized_tail_length ~ SVL * Sex
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     74 1923.1                           
2     73 1899.5  1    23.583 0.9063 0.3442</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="fu">round</span>(<span class="fu">coef</span>(anc_int), <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         SVL     SexMale SVL:SexMale 
      -1.90        0.53       16.59       -0.79 </code></pre>
</div>
</div>
</section>
<section id="centrar-muda-o-que-o-coeficiente-significa" class="slide level2">
<h2>Centrar muda o que o coeficiente significa</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a>lagartos <span class="ot">&lt;-</span> lagartos <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">SVL_c =</span> SVL <span class="sc">-</span> <span class="fu">mean</span>(SVL))</span>
<span id="cb30-2"><a></a><span class="fu">round</span>(<span class="fu">coef</span>(<span class="fu">lm</span>(Autotomized_tail_length <span class="sc">~</span> SVL_c <span class="sc">*</span> Sex, <span class="at">data =</span> lagartos)), <span class="dv">2</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)         SVL_c       SexMale SVL_c:SexMale 
         9.74          0.53         -0.61         -0.79 </code></pre>
</div>
</div>
<div class="definicao">
<p>Sem centrar, <code>SexMale</code> é a diferença entre sexos <strong>em SVL = 0</strong> — um lagarto de tamanho zero. Centrando, passa a ser a diferença <strong>num lagarto de tamanho médio</strong>, que é a comparação que interessa.</p>
</div>
<p>Com interação no modelo, <strong>sempre centre a covariável</strong> antes de interpretar efeitos principais.</p>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="somas-de-quadrados" class="title-slide slide level1 secao center">
<h1>5. Somas de quadrados</h1>

</section>
<section id="por-que-existem-três-tipos" class="slide level2">
<h2>Por que existem três tipos</h2>
<p>Com delineamento <strong>balanceado</strong>, os fatores são ortogonais e a ordem não importa. Com <strong>desbalanceado</strong> — que é o caso de quase todo dado de campo —, a variação compartilhada entre fatores precisa ser atribuída a alguém.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">table</span>(pinguins<span class="sc">$</span>species, pinguins<span class="sc">$</span>sex)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           
            female male
  Adelie        73   73
  Chinstrap     34   34
  Gentoo        58   61</code></pre>
</div>
</div>
</section>
<section id="tipo-i-sequencial" class="slide level2">
<h2>Tipo I: sequencial</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">anova</span>(<span class="fu">lm</span>(body_mass_g <span class="sc">~</span> species <span class="sc">+</span> flipper_length_mm, <span class="at">data =</span> pinguins))[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Df    Sum Sq
species             2 145190219
flipper_length_mm   1  24226302
Residuals         329  45843144</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">anova</span>(<span class="fu">lm</span>(body_mass_g <span class="sc">~</span> flipper_length_mm <span class="sc">+</span> species, <span class="at">data =</span> pinguins))[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Df    Sum Sq
flipper_length_mm   1 164047703
species             2   5368818
Residuals         329  45843144</code></pre>
</div>
</div>
<div class="definicao">
<p>A mesma dupla de preditoras, em ordem trocada, dá somas de quadrados diferentes. O tipo I atribui ao <strong>primeiro</strong> tudo o que é compartilhado.</p>
</div>
</section>
<section id="tipos-ii-e-iii" class="slide level2">
<h2>Tipos II e III</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>car<span class="sc">::</span><span class="fu">Anova</span>(m_int, <span class="at">type =</span> <span class="st">"II"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: body_mass_g
               Sum Sq  Df F value    Pr(&gt;F)    
species     143401584   2 749.016 &lt; 2.2e-16 ***
sex          37090262   1 387.460 &lt; 2.2e-16 ***
species:sex   1676557   2   8.757 0.0001973 ***
Residuals    31302628 327                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><strong>Tipo II</strong>: cada efeito principal ajustado pelos outros efeitos principais, ignorando interações. Bom quando a interação é irrelevante.</li>
<li><strong>Tipo III</strong>: cada termo ajustado por <strong>todos</strong> os outros, interações inclusive. Exige contrastes de soma zero.</li>
</ul>
</section>
<section id="tipo-iii-exige-contr.sum" class="slide level2">
<h2>Tipo III exige <code>contr.sum</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>m_int3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> species <span class="sc">*</span> sex, <span class="at">data =</span> pinguins,</span>
<span id="cb40-2"><a></a>             <span class="at">contrasts =</span> <span class="fu">list</span>(<span class="at">species =</span> <span class="st">"contr.sum"</span>, <span class="at">sex =</span> <span class="st">"contr.sum"</span>))</span>
<span id="cb40-3"><a></a>car<span class="sc">::</span><span class="fu">Anova</span>(m_int3, <span class="at">type =</span> <span class="st">"III"</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: body_mass_g
                Sum Sq Df  F value    Pr(&gt;F)    
(Intercept) 5232595969  1 54661.83 &lt; 2.2e-16 ***
species      143001222  2   746.92 &lt; 2.2e-16 ***
sex           29851220  1   311.84 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="definicao">
<p>Rodar tipo III com o <code>contr.treatment</code> padrão do R produz um teste de efeito principal que <strong>não significa o que você pensa</strong>. É um dos erros mais comuns em artigos de ecologia.</p>
</div>
</section>
<section id="qual-usar" class="slide level2">
<h2>Qual usar</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Situação</th>
<th>Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Balanceado</td>
<td>tanto faz — dão o mesmo</td>
</tr>
<tr class="even">
<td>Desbalanceado, sem interação relevante</td>
<td>II</td>
</tr>
<tr class="odd">
<td>Desbalanceado, interação é a pergunta</td>
<td>III, com <code>contr.sum</code></td>
</tr>
<tr class="even">
<td>Você quer ordem de entrada deliberada (hierárquica)</td>
<td>I, e diga isso no texto</td>
</tr>
</tbody>
</table>
<p><strong>Sempre relate qual tipo usou.</strong> Sem isso, a tabela não é reproduzível.</p>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="comparações" class="title-slide slide level1 secao center">
<h1>6. Comparações</h1>

</section>
<section id="emmeans-médias-marginais-estimadas" class="slide level2">
<h2><code>emmeans</code>: médias marginais estimadas</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb42-2"><a></a><span class="fu">emmeans</span>(m_int, <span class="sc">~</span> sex <span class="sc">|</span> species)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>species = Adelie:
 sex    emmean   SE  df lower.CL upper.CL
 female   3369 36.2 327     3298     3440
 male     4043 36.2 327     3972     4115

species = Chinstrap:
 sex    emmean   SE  df lower.CL upper.CL
 female   3527 53.1 327     3423     3632
 male     3939 53.1 327     3835     4043

species = Gentoo:
 sex    emmean   SE  df lower.CL upper.CL
 female   4680 40.6 327     4600     4760
 male     5485 39.6 327     5407     5563

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Médias ajustadas pelo modelo — não as médias brutas dos grupos.</p>
</section>
<section id="contrastes" class="slide level2">
<h2>Contrastes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a><span class="fu">pairs</span>(<span class="fu">emmeans</span>(m_int, <span class="sc">~</span> sex <span class="sc">|</span> species))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>species = Adelie:
 contrast      estimate   SE  df t.ratio p.value
 female - male     -675 51.2 327 -13.174 &lt;0.0001

species = Chinstrap:
 contrast      estimate   SE  df t.ratio p.value
 female - male     -412 75.0 327  -5.487 &lt;0.0001

species = Gentoo:
 contrast      estimate   SE  df t.ratio p.value
 female - male     -805 56.7 327 -14.188 &lt;0.0001</code></pre>
</div>
</div>
<p>Aqui cada comparação é uma pergunta biológica específica: dimorfismo sexual dentro de cada espécie.</p>
</section>
<section id="planejada-post-hoc" class="slide level2">
<h2>Planejada × post-hoc</h2>
<div class="definicao">
<p><strong>Planejada</strong>: você sabia, antes de coletar, quais comparações interessavam. Poucas, e mais poderosas.</p>
<p><strong>Post-hoc</strong>: você olhou os dados e decidiu o que comparar. Todas contra todas, com correção mais severa.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a><span class="fu">pairs</span>(<span class="fu">emmeans</span>(m, <span class="sc">~</span> species), <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast           estimate   SE  df t.ratio p.value
 Adelie - Chinstrap    -26.9 67.7 330  -0.398  0.9164
 Adelie - Gentoo     -1386.3 56.9 330 -24.359 &lt;0.0001
 Chinstrap - Gentoo  -1359.3 70.0 330 -19.406 &lt;0.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="o-que-a-correção-faz" class="slide level2">
<h2>O que a correção faz</h2>
<ul>
<li><strong>Bonferroni</strong> — divide <span class="math inline">\(\alpha\)</span> pelo número de testes. Conservadora.</li>
<li><strong>Tukey</strong> — desenhada para todas as comparações par a par.</li>
<li><strong>FDR (Benjamini–Hochberg)</strong> — controla a proporção esperada de falsos positivos entre as rejeições. Sensata quando há muitos testes.</li>
</ul>
<div class="nota">
<p>Nenhuma correção conserta o problema de ter decidido as comparações depois de ver os dados. Isso é conteúdo do Encontro 1.</p>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="como-relatar" class="title-slide slide level1 secao center">
<h1>7. Como relatar</h1>

</section>
<section id="o-que-precisa-estar-no-texto" class="slide level2">
<h2>O que precisa estar no texto</h2>
<p>Seguindo Davis &amp; Kay (2023):</p>
<ol type="1">
<li><strong>Objetivo</strong> — a comparação que interessa, em uma frase.</li>
<li><strong>Variáveis</strong> — resposta com unidade; fatores com número de níveis e quantas observações por nível.</li>
<li><strong>Método</strong> — “modelo linear com espécie, sexo e sua interação; somas de quadrados do tipo III com contrastes de soma zero; comparações par a par com correção de Tukey via <code>emmeans</code>”.</li>
<li><strong>Implementação</strong> — versões de R e pacotes.</li>
</ol>
</section>
<section id="tabela-ou-texto" class="slide level2">
<h2>Tabela ou texto?</h2>
<div class="definicao">
<p>Uma tabela de ANOVA sozinha não responde à pergunta biológica. Ela diz “há diferença”; o leitor quer saber <strong>qual</strong> e <strong>de quanto</strong>.</p>
</div>
<p>Relate sempre: a estimativa da diferença, com unidade e intervalo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a><span class="fu">confint</span>(<span class="fu">pairs</span>(<span class="fu">emmeans</span>(m_int, <span class="sc">~</span> sex <span class="sc">|</span> species)))[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">7</span>)]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       contrast   species  estimate  lower.CL  upper.CL
1 female - male    Adelie -674.6575 -775.4037 -573.9114
2 female - male Chinstrap -411.7647 -559.3865 -264.1429
3 female - male    Gentoo -805.0947 -916.7218 -693.4676</code></pre>
</div>
</div>
</section>
<section class="slide level2">

</section></section>
<section>
<section id="fechamento" class="title-slide slide level1 secao center">
<h1>Fechamento</h1>

</section>
<section id="o-que-fica-de-hoje" class="slide level2">
<h2>O que fica de hoje</h2>
<ol type="1">
<li>ANOVA e ANCOVA são <code>lm()</code> com mais colunas — e <code>aov()</code> é uma casca.</li>
<li>A tabela de ANOVA é uma decomposição do <strong>mesmo ajuste</strong>.</li>
<li>Interação é o produto de colunas — e em ecologia costuma ser a pergunta.</li>
<li>Com interação, centre covariáveis e desconfie de efeitos principais.</li>
<li>Somas de quadrados I, II e III diferem em dado desbalanceado; tipo III exige <code>contr.sum</code>.</li>
<li>Relate a <strong>estimativa com intervalo</strong>, não só o <em>p</em>.</li>
</ol>
</section>
<section id="prática-o-resto-do-bloco" class="slide level2">
<h2>Prática (o resto do bloco)</h2>
<ol type="1">
<li>Nos seus dados, ajuste um modelo com dois fatores e interação.</li>
<li>Compare com o aditivo usando <code>anova()</code>.</li>
<li>Faça o gráfico de médias por grupo e diga se as retas são paralelas.</li>
<li>Rode <code>car::Anova()</code> nos tipos II e III e explique qualquer diferença.</li>
<li>Use <code>emmeans</code> para a comparação que <strong>interessa à sua pergunta</strong> — só ela.</li>
</ol>
</section>
<section id="para-a-tarde" class="slide level2">
<h2>Para a tarde</h2>
<p><strong>Leitura:</strong> Agresti (2015), cap. 4.</p>
<p><strong>À tarde:</strong> saímos do mundo gaussiano. Que processo gerou os seus dados?</p>
</section>
<section id="referências" class="slide level2">
<h2>Referências</h2>
<div class="nota">
<ul>
<li>Quinn, G.P. &amp; Keough, M.J. 2023. <a href="https://doi.org/10.1017/9781139568173"><em>Experimental Design and Data Analysis for Biologists</em></a>. 2ª ed.&nbsp;Cambridge University Press.</li>
<li>Gelman, A.; Hill, J. &amp; Vehtari, A. 2020. <a href="https://avehtari.github.io/ROS-Examples/"><em>Regression and Other Stories</em></a>. Cambridge University Press. — código e exemplos no site.</li>
<li>Agresti, A. 2015. <a href="https://www.wiley.com/en-us/Foundations+of+Linear+and+Generalized+Linear+Models-p-9781118730034"><em>Foundations of Linear and Generalized Linear Models</em></a>. Wiley.</li>
<li>Spake, R.; Bowler, D.E.; Callaghan, C.T.; Blowes, S.A.; Doncaster, C.P.; Antão, L.H.; Nakagawa, S.; McElreath, R. &amp; Chase, J.M. 2023. <a href="https://doi.org/10.1111/brv.12939">Understanding ‘it depends’ in ecology: a guide to hypothesising, visualising and interpreting statistical interactions</a>. <em>Biological Reviews</em> 98:983–1002. Acesso aberto.</li>
<li>Davis, S. &amp; Kay, M. 2023. <a href="https://doi.org/10.1002/ecs2.4539">Statistical reporting checklist</a>. <em>Ecosphere</em>.</li>
<li>Lenth, R. <a href="https://cran.r-project.org/package=emmeans"><code>emmeans</code>: estimated marginal means</a>.</li>
<li>da Silva, F.R.; Gonçalves-Souza, T.; Paterno, G.; <strong>Provete, D.B.</strong> &amp; Vancine, M.A.&nbsp;2022. <a href="https://analises-ecologicas.com"><em>Análises Ecológicas no R</em></a>. NUPEEA.</li>
</ul>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Análise de Dados Univariados · PPGBA/UFMS · 2026/2</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: false,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1250,

        height: 750,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiada");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiada");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/provetelab\.org\/analise-dados-univariados-2026-2\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>